name: Mobile Compression

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  compress:
    name: Run ASTC Compressor
    runs-on: [self-hosted, linux]

    permissions:
      contents: write

    steps:
      - name: Download Source Code
        uses: FunkinCrew/ci-checkout@v7.3.3

      - uses: FunkinCrew/ci-haxe@v3
        with:
          haxe-version: 4.3.7

      - name: Install ASTC Compressor
        run: haxelib --quiet --always git astc-compressor https://github.com/TechnikTil/astc-compressor chore/kill-neko

      - name: Retrieve Asset Cache
        id: fetch-asset-cache
        uses: actions/cache/restore@v4
        with:
          path: astc-textures/**
          key: asset-cache

      - name: Run ASTC Compressor
        run: haxelib run astc-compressor compress-from-json -json ./astc-compression-data.json

      - name: Save Asset Cache
        id: save-asset-cache
        uses: actions/cache/save@v4
        with:
          path: astc-textures/**
          key: asset-cache

      - name: Overwrite PNGs with ASTCs
        run: |
          find "astc-textures/" -name "*.astc" -type f | while read -r file; do
            normalFileLoc="${file#astc-textures/}"

            mv "$file" "$normalFileLoc"
            rm "${normalFileLoc%.*}.png"
          done

      - name: Push ASTC Files to `mobile` branch
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Compress Images using ASTC
          branch: mobile
          push_options: '--force'

          file_pattern: '*.astc *.png'

          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
